import { CAPCUT_DEFAULT_FONT_FAMILY, DEFAULT_CAPTION_FONT_FAMILY } from "./captionOptions.mjs";

export const CAPTION_STYLE_TOKENS = {
  "vietnam-bold-highlight": { normalColor: "#20160f", hotColor: "#ff4f2f", strokeColor: "#fffaf0" },
  "karaoke-pill": { normalColor: "#fffdf8", hotColor: "#ffca3a", strokeColor: "#18202e" },
  "clean-outline": { normalColor: "#20160f", hotColor: "#e94d15", strokeColor: "#fffaf0" },
  "impact-pop": { normalColor: "#fffdf8", hotColor: "#ff6b35", strokeColor: "#20160f" },
  "soft-box": { normalColor: "#20160f", hotColor: "#0f766e", strokeColor: "#fffdf8" },
  "neon-glow": { normalColor: "#f7fbff", hotColor: "#ff4cac", strokeColor: "#00d7e7" },
  "capcut-karaoke": { normalColor: "#ffffff", hotColor: "#ffe600", strokeColor: "#000000" },
};

export const CAPTION_PRESETS = [
  {
    id: "orange-word-pop",
    name: "Cam nảy từng từ",
    description: "Mẫu đang dùng: chữ đậm, từ khóa cam, đọc tới đâu bật tới đó.",
    style: "vietnam-bold-highlight",
    animation: "word-pop",
    fontSize: 72,
    captionY: 790,
  },
  {
    id: "karaoke-dark",
    name: "Karaoke nền tối",
    description: "Phụ đề dạng pill đen, nổi rõ khi nền nhiều chi tiết.",
    style: "karaoke-pill",
    animation: "word-pop",
    fontSize: 68,
    captionY: 800,
  },
  {
    id: "clean-compact",
    name: "Gọn viền trắng",
    description: "Ít chiếm khung hình, hợp video cần nhìn rõ nhân vật và ảnh.",
    style: "clean-outline",
    animation: "line-pop",
    fontSize: 66,
    captionY: 780,
  },
  {
    id: "impact-short",
    name: "Impact câu ngắn",
    description: "Chữ trắng viền đậm, dùng cho câu hook hoặc punchline.",
    style: "impact-pop",
    animation: "line-pop",
    fontSize: 76,
    captionY: 805,
  },
  {
    id: "soft-card",
    name: "Box sáng mềm",
    description: "Có nền sáng phía sau chữ, dễ đọc khi ảnh phía sau rối.",
    style: "soft-box",
    animation: "line-pop",
    fontSize: 64,
    captionY: 820,
  },
  {
    id: "neon-tiktok",
    name: "Neon nổi bật",
    description: "Viền phát sáng, hợp video cần cảm giác năng động hơn.",
    style: "neon-glow",
    animation: "word-pop",
    fontSize: 66,
    captionY: 800,
  },
  {
    id: "capcut-viral-karaoke",
    name: "CapCut Viral Karaoke",
    description: "Chữ trắng viền đen dày, đọc tới từ nào thì từ đó vàng.",
    style: "capcut-karaoke",
    animation: "word-color",
    fontFamily: CAPCUT_DEFAULT_FONT_FAMILY,
    fontSize: 74,
    strokeWidth: 12,
    wordGap: 4,
    uppercase: true,
    shadowPreset: "capcut-heavy",
    captionY: 900,
  },
  {
    id: "vn-news-black",
    name: "VN News Black",
    description: "Nata Sans rõ chữ, hợp video kiến thức cần đọc nhanh.",
    style: "clean-outline",
    animation: "word-color",
    fontFamily: "Nata Sans",
    fontSize: 70,
    normalColor: "#171411",
    hotColor: "#d93814",
    strokeColor: "#fffaf0",
    strokeWidth: 8,
    captionY: 790,
  },
  {
    id: "vn-karaoke-baloo",
    name: "VN Karaoke Baloo",
    description: "Baloo 2 mềm và dễ đọc, từ đang đọc nhảy nhẹ.",
    style: "karaoke-pill",
    animation: "word-pop",
    fontFamily: "Baloo 2",
    fontSize: 70,
    normalColor: "#fffdf8",
    hotColor: "#ffdf3f",
    strokeColor: "#18202e",
    strokeWidth: 10,
    wordGap: 3,
    captionY: 812,
  },
  {
    id: "vn-capcut-public",
    name: "VN CapCut Public",
    description: "Public Sans viết hoa, viền đen dày theo kiểu CapCut.",
    style: "capcut-karaoke",
    animation: "word-color",
    fontFamily: "Public Sans",
    fontSize: 74,
    normalColor: "#ffffff",
    hotColor: "#ffe600",
    strokeColor: "#000000",
    strokeWidth: 12,
    wordGap: 4,
    uppercase: true,
    shadowPreset: "capcut-heavy",
    captionY: 900,
  },
  {
    id: "vn-hook-bungee",
    name: "VN Hook Bungee",
    description: "Bungee cho hook rất ngắn, nổi mạnh ở đầu video.",
    style: "impact-pop",
    animation: "line-pop",
    fontFamily: "Bungee",
    fontSize: 68,
    normalColor: "#fffdf8",
    hotColor: "#fff3ab",
    strokeColor: "#20160f",
    strokeWidth: 12,
    uppercase: true,
    shadowPreset: "default",
    captionY: 805,
  },
  {
    id: "vn-tech-chakra",
    name: "VN Tech Chakra",
    description: "Chakra Petch góc cạnh, hợp nội dung tech hoặc data.",
    style: "neon-glow",
    animation: "word-color",
    fontFamily: "Chakra Petch",
    fontSize: 68,
    normalColor: "#f7fbff",
    hotColor: "#ff4cac",
    strokeColor: "#00d7e7",
    strokeWidth: 8,
    wordGap: 2,
    captionY: 800,
  },
  {
    id: "vn-soft-noto",
    name: "VN Soft Noto",
    description: "Noto Sans trong box sáng, an toàn trên nền rối.",
    style: "soft-box",
    animation: "line-pop",
    fontFamily: "Noto Sans",
    fontSize: 66,
    normalColor: "#20160f",
    hotColor: "#0f766e",
    strokeColor: "#fffdf8",
    strokeWidth: 6,
    captionY: 820,
  },
];

export function applyCaptionPreset(draft, preset) {
  const tokens = {
    ...(CAPTION_STYLE_TOKENS[preset.style] || {}),
    ...(preset.normalColor ? { normalColor: preset.normalColor } : {}),
    ...(preset.hotColor ? { hotColor: preset.hotColor } : {}),
    ...(preset.strokeColor ? { strokeColor: preset.strokeColor } : {}),
  };
  const wordGap = Number(preset.wordGap);
  const strokeWidth = Number(preset.strokeWidth);

  draft.caption = {
    ...(draft.caption || {}),
    ...tokens,
    presetId: preset.id,
    style: preset.style,
    animation: preset.animation,
    fontSize: Number.isFinite(Number(preset.fontSize)) ? Number(preset.fontSize) : (draft.caption?.fontSize || 72),
    fontFamily: preset.fontFamily || DEFAULT_CAPTION_FONT_FAMILY,
    strokeWidth: Number.isFinite(strokeWidth) ? strokeWidth : 10,
    wordGap: Number.isFinite(wordGap) ? wordGap : 0,
    uppercase: Boolean(preset.uppercase),
    shadowPreset: preset.shadowPreset || "default",
  };
  draft.layout = {
    ...(draft.layout || {}),
    captionY: Number.isFinite(Number(preset.captionY)) ? Number(preset.captionY) : (draft.layout?.captionY || 810),
    captionYExplicit: true,
  };
  draft.character = {
    ...(draft.character || {}),
    captionFontFamily: draft.caption.fontFamily,
  };
}
